name:                ghci4luatex
version:             0.1
github:              "AliceRixte/ghci4luatex"
license:             BSD3
author:              "Alice Rixte"
maintainer:          "alice.rixte@u-bordeaux.fr"
copyright:           "Alice Rixte 2024"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            media

description:         Please see the README on GitHub at <https://github.com/AliceRixte/pandia/blob/main/ghci4luatex#readme>


dependencies:
- base >= 4.18 && < 5
- process >= 1.6.25 && < 1.7
- network-simple >= 0.4 && < 0.5
- stm >= 2.5 && < 2.6
- bytestring >= 0.12 && < 0.13
- aeson >= 2.2 && < 2.3
- text >= 2.1 && < 2.2
- cmdargs >= 0.10 && < 0.11
- containers >= 0.6 && < 0.7

ghc-options:
- -Wall


library:
  source-dirs: src

executables:
  ghci4luatex:
    main:                ghci4luatex.hs
    source-dirs:         app
    dependencies:
    - ghci4luatex
    ghc-options:
    - -rtsopts
    - -with-rtsopts=-N
    - -threaded

tests:
  ghci4luatex-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hspec >= 2.11
    - QuickCheck
    - ghci4luatex

